---
- name: Install aptitude
  become: True
  apt:
    name:
      - aptitude

- name: Configure installation of recommended and suggested packages
  become: True
  template:
    src: 90recommended-packages.j2
    dest: /etc/apt/apt.conf.d/90recommended-packages

- name: Configure additional repositories
  become: True
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_additional_repositories }}"

- name: Configure apt pins
  become: True
  template:
    src: pin.j2
    dest: "/etc/apt/preferences.d/ansible-pins"
